#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : pypi-regress
Version  : 2024.11.1
Release  : 4
URL      : https://files.pythonhosted.org/packages/6a/66/48fe4e8d5b14f9d5ac394b4f8847c1cf69f8c1cfa4c2b216f570f0114f97/regress-2024.11.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/6a/66/48fe4e8d5b14f9d5ac394b4f8847c1cf69f8c1cfa4c2b216f570f0114f97/regress-2024.11.1.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-regress/snapshot/pypi-regress-2024-11-15-23-55-17.tar.gz
Summary  : Python bindings to Rust's regress ECMA regular expressions library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause MIT Unicode-DFS-2016 Unlicense
Requires: pypi-regress-license = %{version}-%{release}
Requires: pypi-regress-python = %{version}-%{release}
Requires: pypi-regress-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===========
``regress``
===========
|PyPI| |Pythons| |CI|
.. |PyPI| image:: https://img.shields.io/pypi/v/regress.svg
:alt: PyPI version
:target: https://pypi.org/project/regress/

%package license
Summary: license components for the pypi-regress package.
Group: Default

%description license
license components for the pypi-regress package.


%package python
Summary: python components for the pypi-regress package.
Group: Default
Requires: pypi-regress-python3 = %{version}-%{release}

%description python
python components for the pypi-regress package.


%package python3
Summary: python3 components for the pypi-regress package.
Group: Default
Requires: python3-core
Provides: pypi(regress)

%description python3
python3 components for the pypi-regress package.


%prep
%setup -q -n regress-2024.11.1
cd %{_builddir}
tar xf %{_sourcedir}/pypi-regress-2024-11-15-23-55-17.tar.gz
cd %{_builddir}/regress-2024.11.1
mkdir -p ./vendor
cp -r %{_builddir}/pypi-regress-2024-11-15-23-55-17/* %{_builddir}/regress-2024.11.1/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738273264
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-regress
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/ahash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/ahash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/2646b6d2453275031022ab245a3a6d5da4ba80b2 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/allocator-api2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/96c0ace4eb1b0a78134d978d3c6d656a860a670f || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/memchr/COPYING %{buildroot}/usr/share/package-licenses/pypi-regress/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-regress/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-regress/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/python3-dll-a/LICENSE %{buildroot}/usr/share/package-licenses/pypi-regress/dc343e169fac680f93f90bc6cc63ca0c7a460131 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/regress/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/c43025bca3f7d7f985c06efcea467aecfaf9ccf1 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/regress/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/f48aaaf87a9548b8a5842dc9f34c846aee9c3420 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-regress/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-regress/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-regress/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-regress/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-regress-2024-11-15-23-55-17/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/regress-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-regress/30a3d7eda1e8880325b611de40e44026ed5866ea || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-regress/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-regress/2646b6d2453275031022ab245a3a6d5da4ba80b2
/usr/share/package-licenses/pypi-regress/30a3d7eda1e8880325b611de40e44026ed5866ea
/usr/share/package-licenses/pypi-regress/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-regress/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-regress/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/pypi-regress/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/pypi-regress/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-regress/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-regress/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-regress/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-regress/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-regress/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-regress/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-regress/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-regress/96c0ace4eb1b0a78134d978d3c6d656a860a670f
/usr/share/package-licenses/pypi-regress/c43025bca3f7d7f985c06efcea467aecfaf9ccf1
/usr/share/package-licenses/pypi-regress/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/pypi-regress/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-regress/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/pypi-regress/dc343e169fac680f93f90bc6cc63ca0c7a460131
/usr/share/package-licenses/pypi-regress/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-regress/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-regress/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/pypi-regress/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-regress/f48aaaf87a9548b8a5842dc9f34c846aee9c3420
/usr/share/package-licenses/pypi-regress/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
